=== reyesdefedericocarlota/Lenguaje-de-marcas/Tema 1/Repaso/repasoxsd/ejercicio8.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="redSocial">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="usuario" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nombreUsuario">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:minLength value="3" />
                                        <xs:maxLength value="15" />
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="email">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern
                                            value="[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}" />
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="seguidores">
                                <xs:simpleType>
                                    <xs:restriction base="xs:integer">
                                        <xs:minInclusive value="0" />
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="publicacion" minOccurs="0" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="titulo" type="xs:string" />
                                        <xs:element name="fecha" type="xs:date" />
                                        <xs:element name="likes" type="xs:positiveInteger" />
                                        <xs:element name="comentario" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="autor" type="xs:string" />
                                                    <xs:element name="contenido" type="xs:string" />
                                                    <xs:element name="fecha" type="xs:dateTime" />
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="id" use="required" type="xs:positiveInteger" />
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== reyesdefedericocarlota/Lenguaje-de-marcas/Tema 1/Repaso/repasoxsd/ejercicio8.xml
<?xml version="1.0" encoding="UTF-8"?>
<redSocial xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="ejercicio8.xsd">
    <usuario id="4">
        <nombreUsuario>carlota_defed</nombreUsuario>
        <email>carlota.reyesdefed@gmail.com</email>
        <seguidores>750</seguidores>
        <publicacion>
            <titulo>Verano 2025</titulo>
            <fecha>2025-08-14</fecha>
            <likes>100</likes>
            <comentario>
                <autor>rangelitojb</autor>
                <contenido>El mejor veranoo</contenido>
                <fecha>2025-08-14T16:30:00</fecha>
            </comentario>
        </publicacion>
    </usuario>
    <usuario id="7">
        <nombreUsuario>teresa.rdf</nombreUsuario>
        <email>teresa.rdf@gmail.com</email>
        <seguidores>425</seguidores>
    </usuario>
    <usuario id="23">
        <nombreUsuario>izanagi.02</nombreUsuario>
        <email>izan02_ar@gmail.com</email>
        <seguidores>128</seguidores>
        <publicacion>
            <titulo>Paseo por la Alhambra</titulo>
            <fecha>2025-10-21</fecha>
            <likes>55</likes>
        </publicacion>
    </usuario>
</redSocial>
