=== reyesdefedericocarlota/Lenguaje-de-marcas/Tema 1/Repaso/repasoxsd/ejercicio7.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="reservas">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="reserva">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="cliente">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="nombre">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:pattern value="[A-Z][A-Za-záéíóú| ]+" />
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="dni">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:pattern value="\d{8}[A-Z]" />
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="habitacion">
                                <xs:complexType>
                                    <xs:attribute name="tipo">
                                        <xs:simpleType>
                                            <xs:restriction base="xs:string">
                                                <xs:enumeration value="Individual" />
                                                <xs:enumeration value="Doble" />
                                                <xs:enumeration value="Suite" />
                                            </xs:restriction>
                                        </xs:simpleType>
                                    </xs:attribute>
                                    <xs:attribute name="numero" type="xs:positiveInteger" />
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="fechaEntrada" type="xs:date" />
                            <xs:element name="fechaSalida" type="xs:date" />
                            <xs:element name="precioTotal">
                                <xs:simpleType>
                                    <xs:restriction base="xs:decimal">
                                        <xs:minInclusive value="50" />
                                        <xs:maxInclusive value="5000" />
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="codigo" use="required">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:pattern value="R\d{3}" />
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== reyesdefedericocarlota/Lenguaje-de-marcas/Tema 1/Repaso/repasoxsd/ejercicio7.xml
<?xml version="1.0" encoding="UTF-8"?>
<reservas xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="ejercicio7.xsd">
  <reserva codigo="R001">
    <cliente>
      <nombre>Lucía Martínez</nombre>
      <dni>12345678Z</dni>
    </cliente>
    <habitacion tipo="Doble" numero="202" />
    <fechaEntrada>2025-07-01</fechaEntrada>
    <fechaSalida>2025-07-05</fechaSalida>
    <precioTotal>480.50</precioTotal>
  </reserva>
</reservas>
