=== reyesdefedericocarlota/Lenguaje-de-marcas/Tema 1/Relación 4/ejercicio4-4.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="clase">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="alumno" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nombre">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="[A-Z][A-Za-z| ]+" />
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="edad">
                                <xs:simpleType>
                                    <xs:restriction base="xs:integer">
                                        <xs:minInclusive value="6" />
                                        <xs:maxInclusive value="18" />
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="nota" minOccurs="1" maxOccurs="5">
                                <xs:simpleType>
                                    <xs:restriction base="xs:decimal">
                                        <xs:minInclusive value="0" />
                                        <xs:maxInclusive value="10" />
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="dni">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="\d{8}[A-Z]" />
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="id" type="xs:positiveInteger" />
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== reyesdefedericocarlota/Lenguaje-de-marcas/Tema 1/Relación 4/ejercicio4-4.xml
<?xml version="1.0" encoding="UTF-8"?>
<clase xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="ejercicio4-4.xsd">
    <alumno>
        <nombre>Carlota Reyes de Federico</nombre>
        <edad>18</edad>
        <nota>9</nota>
        <nota>8.5</nota>
        <nota>7.45</nota>
        <dni>78110247Q</dni>
    </alumno>
    <alumno>
        <nombre>Ángel López Rodriguez</nombre>
        <edad>16</edad>
        <nota>6.5</nota>
        <nota>10</nota>
        <nota>8</nota>
        <nota>5.4</nota>
        <nota>7</nota>
        <dni>65982309A</dni>
    </alumno>
</clase>
